#!/bin/bash
#until format
#until condition
#do
# statement
#done

until who | grep "$1" > /dev/null
do
    sleep 1
done

#now ring the bell and announce the expected user.

echo -e \\a

echo "****$1 has just logged in****"

exit 0

