#!/bin/bash

echo "Is it morning? Please answer yes or no"

read time

if [ "$time" = "yes" ]
then
    echo "Good Morning"
elif [ "$time" = "no" ]
then
    echo "Good afternoon"
else
    echo "sorry, $time not recognized. Enter yes or no"
    exit 1
fi
exit 0
