#!/bin/sh

salutation="hello"
echo $salutation
echo "The program $0 is now running"
echo "The first parameter was $1"
echo "The second parameter was $2"
echo "The list of  parameter was $*"
echo "The user's home directory is $HOME"
echo "Please enter a new greeting"
read salutation
echo $salutation
echo "The script is now complete"
exit 0
